export const AMAZON_REFERRAL_FEES: Record<string, { percentage: number; minimumFee: number }> = {
  'Amazon Device Accessories': { percentage: 45, minimumFee: 0.30 },
  'Appliances': { percentage: 15, minimumFee: 0.30 },
  'Arts, Crafts & Sewing': { percentage: 15, minimumFee: 0.30 },
  'Automotive & Powersports': { percentage: 12, minimumFee: 0.30 },
  'Baby Products': { percentage: 8, minimumFee: 0.30 },
  'Beauty & Personal Care': { percentage: 8, minimumFee: 0.30 },
  'Books': { percentage: 15, minimumFee: 0 },
  'Clothing & Accessories': { percentage: 17, minimumFee: 0.30 },
  'Computers & Accessories': { percentage: 8, minimumFee: 0.30 },
  'Consumer Electronics': { percentage: 8, minimumFee: 0.30 },
  'Electronics Accessories': { percentage: 15, minimumFee: 0.30 },
  'Everything Else': { percentage: 15, minimumFee: 0.30 },
  'Grocery & Gourmet Food': { percentage: 8, minimumFee: 0 },
  'Health & Household': { percentage: 8, minimumFee: 0.30 },
  'Home & Kitchen': { percentage: 15, minimumFee: 0.30 },
  'Jewelry': { percentage: 20, minimumFee: 0.30 },
  'Lawn & Garden': { percentage: 15, minimumFee: 0.30 },
  'Musical Instruments': { percentage: 15, minimumFee: 0.30 },
  'Office Products': { percentage: 15, minimumFee: 0.30 },
  'Pet Supplies': { percentage: 15, minimumFee: 0.30 },
  'Sports & Outdoors': { percentage: 15, minimumFee: 0.30 },
  'Tools & Home Improvement': { percentage: 15, minimumFee: 0.30 },
  'Toys & Games': { percentage: 15, minimumFee: 0.30 },
  'Video Games': { percentage: 15, minimumFee: 0 },
  'Watches': { percentage: 16, minimumFee: 0.30 },
  'Default': { percentage: 15, minimumFee: 0.30 },
};
