export const WALMART_REFERRAL_FEES: Record<string, { percentage: number }> = {
  'Apparel': { percentage: 15 },
  'Automotive': { percentage: 12 },
  'Baby': { percentage: 8 },
  'Beauty': { percentage: 15 },
  'Books': { percentage: 15 },
  'Electronics': { percentage: 8 },
  'Furniture': { percentage: 15 },
  'Grocery': { percentage: 8 },
  'Health': { percentage: 15 },
  'Home': { percentage: 15 },
  'Jewelry': { percentage: 20 },
  'Office': { percentage: 15 },
  'Personal Computers': { percentage: 6 },
  'Pet Supplies': { percentage: 15 },
  'Sports & Outdoors': { percentage: 15 },
  'Tools': { percentage: 15 },
  'Toys': { percentage: 15 },
  'Video Games': { percentage: 15 },
  'Default': { percentage: 15 },
};
