export const AMAZON_REFERRAL_FEE_CATEGORIES: Record<string, { percentage: number; minimumFee: number }> = {
  'Amazon Device Accessories': { percentage: 45, minimumFee: 0.30 },
  'Appliances': { percentage: 15, minimumFee: 0.30 },
  'Apps & Games': { percentage: 20, minimumFee: 0 },
  'Arts, Crafts & Sewing': { percentage: 15, minimumFee: 0.30 },
  'Automotive & Powersports': { percentage: 12, minimumFee: 0.30 },
  'Baby Products': { percentage: 8, minimumFee: 0.30 },
  'Backpacks, Handbags & Luggage': { percentage: 15, minimumFee: 0.30 },
  'Beauty & Personal Care': { percentage: 8, minimumFee: 0.30 },
  'Books': { percentage: 15, minimumFee: 0 },
  'Business, Industrial & Scientific': { percentage: 12, minimumFee: 0.30 },
  'Clothing & Accessories': { percentage: 17, minimumFee: 0.30 },
  'Collectible Coins': { percentage: 15, minimumFee: 0.30 },
  'Compact Appliances': { percentage: 15, minimumFee: 0.30 },
  'Computers & Accessories': { percentage: 8, minimumFee: 0.30 },
  'Consumer Electronics': { percentage: 8, minimumFee: 0.30 },
  'Electronics Accessories': { percentage: 15, minimumFee: 0.30 },
  'Everything Else': { percentage: 15, minimumFee: 0.30 },
  'Eyewear': { percentage: 15, minimumFee: 0.30 },
  'Fine Art': { percentage: 20, minimumFee: 0 },
  'Footwear': { percentage: 15, minimumFee: 0.30 },
  'Full-Size Appliances': { percentage: 8, minimumFee: 0.30 },
  'Furniture': { percentage: 15, minimumFee: 0.30 },
  'Gift Cards': { percentage: 20, minimumFee: 0 },
  'Grocery & Gourmet Food': { percentage: 8, minimumFee: 0 },
  'Health & Household': { percentage: 8, minimumFee: 0.30 },
  'Home & Kitchen': { percentage: 15, minimumFee: 0.30 },
  'Jewelry': { percentage: 20, minimumFee: 0.30 },
  'Kitchen': { percentage: 15, minimumFee: 0.30 },
  'Lawn & Garden': { percentage: 15, minimumFee: 0.30 },
  'Lawn Mowers & Snow Throwers': { percentage: 15, minimumFee: 0.30 },
  'Mattresses': { percentage: 15, minimumFee: 0.30 },
  'Media - Books, DVD, Music, Software, Video': { percentage: 15, minimumFee: 0 },
  'Musical Instruments': { percentage: 15, minimumFee: 0.30 },
  'Office Products': { percentage: 15, minimumFee: 0.30 },
  'Outdoors': { percentage: 15, minimumFee: 0.30 },
  'Personal Computers': { percentage: 6, minimumFee: 0.30 },
  'Pet Supplies': { percentage: 15, minimumFee: 0.30 },
  'Sports & Outdoors': { percentage: 15, minimumFee: 0.30 },
  'Tires': { percentage: 10, minimumFee: 0.30 },
  'Tools & Home Improvement': { percentage: 15, minimumFee: 0.30 },
  'Toys & Games': { percentage: 15, minimumFee: 0.30 },
  'Video Game Consoles': { percentage: 8, minimumFee: 0 },
  'Video Games': { percentage: 15, minimumFee: 0 },
  'Watches': { percentage: 16, minimumFee: 0.30 },
  'Default': { percentage: 15, minimumFee: 0.30 },
};
