#!/usr/bin/env bash
# Create or reuse a Neon project named "sourcetool" and write connection
# strings to .env.neon (gitignored). Requires NEON_API_KEY from
# https://console.neon.tech → Account settings → API keys.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

NEON=(npx --yes neonctl@2 --output json)
NAME="${NEON_PROJECT_NAME:-sourcetool}"
REGION="${NEON_REGION:-aws-us-east-1}"
PG_VERSION="${NEON_PG_VERSION:-16}"
DATABASE="${NEON_DATABASE:-sourcetool}"
OUT="${NEON_ENV_FILE:-$ROOT/.env.neon}"

if [ -z "${NEON_API_KEY:-}" ]; then
  echo "NEON_API_KEY is not set."
  echo "Create a personal key at https://console.neon.tech/app/settings/api-keys"
  echo "then re-run: NEON_API_KEY=napi_... pnpm db:neon:provision"
  exit 1
fi

echo "Listing Neon projects…"
LIST="$("${NEON[@]}" projects list)"
PROJECT_ID="$(python3 - "$LIST" "$NAME" <<'PY'
import json, sys
data = json.loads(sys.argv[1])
name = sys.argv[2]
projects = data.get("projects") or data.get("items") or data
if isinstance(projects, dict):
    projects = projects.get("projects") or []
match = next((p for p in projects if p.get("name") == name), None)
print(match["id"] if match else "")
PY
)"

if [ -n "$PROJECT_ID" ]; then
  echo "Reusing existing Neon project $NAME ($PROJECT_ID)"
else
  echo "Creating Neon project $NAME (pg$PG_VERSION, $REGION, db=$DATABASE)…"
  CREATED="$("${NEON[@]}" projects create --name "$NAME" --region-id "$REGION" --pg-version "$PG_VERSION" --database "$DATABASE")"
  PROJECT_ID="$(python3 - "$CREATED" <<'PY'
import json, sys
data = json.loads(sys.argv[1])
project = data.get("project") or data
print(project["id"])
PY
)"
  echo "Created $PROJECT_ID"
fi

echo "Fetching Prisma pooled + direct connection strings…"
POOLED="$("${NEON[@]}" connection-string --project-id "$PROJECT_ID" --database-name "$DATABASE" --pooled --prisma)"
DIRECT="$("${NEON[@]}" connection-string --project-id "$PROJECT_ID" --database-name "$DATABASE")"

# neonctl --output json for connection-string may still be a raw string
POOLED="$(python3 - "$POOLED" <<'PY'
import json, sys
raw = sys.argv[1].strip()
try:
    data = json.loads(raw)
except json.JSONDecodeError:
    print(raw)
    raise SystemExit
if isinstance(data, str):
    print(data)
else:
    print(data.get("connection_string") or data.get("uri") or data.get("url") or raw)
PY
)"
DIRECT="$(python3 - "$DIRECT" <<'PY'
import json, sys
raw = sys.argv[1].strip()
try:
    data = json.loads(raw)
except json.JSONDecodeError:
    print(raw)
    raise SystemExit
if isinstance(data, str):
    print(data)
else:
    print(data.get("connection_string") or data.get("uri") or data.get("url") or raw)
PY
)"

python3 - "$OUT" "$POOLED" "$DIRECT" "$PROJECT_ID" <<'PY'
import sys
from pathlib import Path
from urllib.parse import urlparse
out, pooled, direct, project_id = sys.argv[1:5]
Path(out).write_text(
    f"# Generated by scripts/neon-provision.sh — do not commit\n"
    f"NEON_PROJECT_ID={project_id}\n"
    f"DATABASE_URL={pooled}\n"
    f"DIRECT_DATABASE_URL={direct}\n"
    f"DATABASE_URL_UNPOOLED={direct}\n"
)
for label, url in (("pooled", pooled), ("direct", direct)):
    p = urlparse(url)
    print(f"{label} host: {p.hostname}  db: {p.path.lstrip('/')}")
print(f"wrote {out}")
print(f"project: {project_id}")
PY

if [ "${NEON_MIGRATE:-1}" = "1" ]; then
  echo "Applying Prisma migrations to the new Neon database…"
  set -a
  # shellcheck disable=SC1090
  source "$OUT"
  set +a
  pnpm --filter @sourcetool/db run db:generate
  pnpm --filter @sourcetool/db run db:migrate:deploy
fi

echo
echo "Next: paste DATABASE_URL and DIRECT_DATABASE_URL from $OUT into Vercel"
echo "(or connect the Neon Vercel integration — aliases are mapped automatically)."
