#!/usr/bin/env bash
# Create or reuse a Neon project named "sourcetool" and write connection
# strings to .env.neon (gitignored). Requires NEON_API_KEY from
# https://console.neon.tech → Account settings → API keys.
#
# Vercel-managed Neon orgs cannot create projects via the API
# (`organization is managed by Vercel`). Default create org is the first
# console-managed org. Override with NEON_ORG_ID.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

NAME="${NEON_PROJECT_NAME:-sourcetool}"
REGION="${NEON_REGION:-aws-us-east-1}"
PG_VERSION="${NEON_PG_VERSION:-16}"
DATABASE="${NEON_DATABASE:-sourcetool}"
OUT="${NEON_ENV_FILE:-$ROOT/.env.neon}"

neon() {
  npx --yes neonctl@2 --output json "$@"
}

load_env_file() {
  # Override any pre-existing DATABASE_URL (e.g. local test Postgres).
  eval "$(python3 - "$1" <<'PY'
from pathlib import Path
from shlex import quote
import sys
for line in Path(sys.argv[1]).read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, v = line.split("=", 1)
    print(f"export {k}={quote(v)}")
PY
)"
}

if [ -z "${NEON_API_KEY:-}" ]; then
  echo "NEON_API_KEY is not set."
  echo "Create a personal key at https://console.neon.tech/app/settings/api-keys"
  echo "then re-run: NEON_API_KEY=napi_... pnpm db:neon:provision"
  exit 1
fi

ORGS="$(neon orgs list)"
ORG_ID="${NEON_ORG_ID:-}"
if [ -z "$ORG_ID" ]; then
  ORG_ID="$(python3 - "$ORGS" <<'PY'
import json, sys
orgs = json.loads(sys.argv[1])
if isinstance(orgs, dict):
    orgs = orgs.get("organizations") or orgs.get("orgs") or []
console = [o for o in orgs if o.get("managed_by") != "vercel"]
chosen = (console or orgs)[0]
print(chosen["id"])
print(f"Using org {chosen.get('name')} ({chosen['id']})", file=sys.stderr)
PY
)"
fi

echo "Listing Neon projects in $ORG_ID…"
LIST="$(neon projects list --org-id "$ORG_ID")"
PROJECT_ID="$(python3 - "$LIST" "$NAME" <<'PY'
import json, sys
data = json.loads(sys.argv[1])
name = sys.argv[2]
projects = data if isinstance(data, list) else data.get("projects") or data.get("items") or []
match = next((p for p in projects if p.get("name") == name), None)
print(match["id"] if match else "")
PY
)"

if [ -n "$PROJECT_ID" ]; then
  echo "Reusing existing Neon project $NAME ($PROJECT_ID)"
else
  echo "Creating Neon project $NAME (pg$PG_VERSION, $REGION, db=$DATABASE)…"
  CREATED="$(neon projects create --org-id "$ORG_ID" --name "$NAME" --region-id "$REGION" --pg-version "$PG_VERSION" --database "$DATABASE")"
  PROJECT_ID="$(python3 - "$CREATED" <<'PY'
import json, sys
data = json.loads(sys.argv[1])
project = data.get("project") or data
print(project["id"])
PY
)"
  echo "Created $PROJECT_ID"
fi

echo "Fetching Prisma pooled + direct connection strings…"
POOLED="$(npx --yes neonctl@2 connection-string --org-id "$ORG_ID" --project-id "$PROJECT_ID" --database-name "$DATABASE" --pooled --prisma)"
DIRECT="$(npx --yes neonctl@2 connection-string --org-id "$ORG_ID" --project-id "$PROJECT_ID" --database-name "$DATABASE")"

python3 - "$OUT" "$POOLED" "$DIRECT" "$PROJECT_ID" "$ORG_ID" <<'PY'
import sys
from pathlib import Path
from urllib.parse import urlparse
out, pooled, direct, project_id, org_id = sys.argv[1:6]
Path(out).write_text(
    "# Generated by scripts/neon-provision.sh — do not commit\n"
    f"NEON_PROJECT_ID={project_id}\n"
    f"NEON_ORG_ID={org_id}\n"
    f"DATABASE_URL={pooled.strip()}\n"
    f"DIRECT_DATABASE_URL={direct.strip()}\n"
    f"DATABASE_URL_UNPOOLED={direct.strip()}\n"
)
for label, url in (("pooled", pooled), ("direct", direct)):
    p = urlparse(url.strip())
    print(f"{label} host: {p.hostname}  db: {p.path.lstrip('/')}")
print(f"wrote {out}")
print(f"project: {project_id}")
PY
chmod 600 "$OUT"

if [ "${NEON_MIGRATE:-1}" = "1" ]; then
  echo "Applying Prisma migrations to the Neon database…"
  load_env_file "$OUT"
  pnpm --filter @sourcetool/db run db:generate
  pnpm --filter @sourcetool/db run db:migrate:deploy
fi

echo
echo "Next: paste DATABASE_URL and DIRECT_DATABASE_URL from $OUT into Vercel."
